// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMlQpR5BbOvuwvjdTBr4gkj5WmFbU-uHY',
    appId: '1:491902988523:web:cdba0f67bb9be518bb0eae',
    messagingSenderId: '491902988523',
    projectId: 'evee-survey-administration-app',
    authDomain: 'evee-survey-administration-app.firebaseapp.com',
    storageBucket: 'evee-survey-administration-app.appspot.com',
    measurementId: 'G-8NYJWMRJ9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlADPshAkYak_6bavhX9ryYSYKDCZr30w',
    appId: '1:491902988523:android:93f4bdf51c409f9fbb0eae',
    messagingSenderId: '491902988523',
    projectId: 'evee-survey-administration-app',
    storageBucket: 'evee-survey-administration-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmIDBp4HMG8GuExmYFaO3NKfeIb5sqlg',
    appId: '1:491902988523:ios:eea1f9475dfc17a6bb0eae',
    messagingSenderId: '491902988523',
    projectId: 'evee-survey-administration-app',
    storageBucket: 'evee-survey-administration-app.appspot.com',
    iosClientId: '491902988523-jbijovho0jrndh43ni52lhpgqqkf9ta9.apps.googleusercontent.com',
    iosBundleId: 'com.example.evee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmIDBp4HMG8GuExmYFaO3NKfeIb5sqlg',
    appId: '1:491902988523:ios:eea1f9475dfc17a6bb0eae',
    messagingSenderId: '491902988523',
    projectId: 'evee-survey-administration-app',
    storageBucket: 'evee-survey-administration-app.appspot.com',
    iosClientId: '491902988523-jbijovho0jrndh43ni52lhpgqqkf9ta9.apps.googleusercontent.com',
    iosBundleId: 'com.example.evee',
  );
}
